import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ReduxProvider from "./reduxProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "LeetClub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark ">
      <body className="m-auto">
      <ReduxProvider>
        <Navbar/>
        <div>{children}</div>
      </ReduxProvider>
      <Toaster/>
      </body>
    </html>
  );
}
